# Generated by Django 4.0.6 on 2022-07-05 18:43

import audio_book.models
import audio_book.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='Collections', max_length=50)),
                ('book_cover', models.ImageField(upload_to=audio_book.models.books_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('book_description', models.TextField(blank=True, max_length=100, null=True)),
                ('book_release_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Other', max_length=120)),
                ('category_description', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrator_name', models.CharField(default='unknown', max_length=50)),
                ('narrator_avatar', models.ImageField(blank=True, null=True, upload_to=audio_book.models.narrators_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('narrator_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Narrator',
                'verbose_name_plural': 'Narratores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default='unknown', max_length=50)),
                ('writer_avatar', models.ImageField(blank=True, null=True, upload_to=audio_book.models.writers_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('writer_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(default='Unknown_chapter', max_length=120)),
                ('chapter_description', models.TextField(blank=True, max_length=100, null=True)),
                ('chapter_file', models.FileField(null=True, upload_to=audio_book.models.chapter_files, validators=[audio_book.validators.validate_track_extension])),
                ('user', models.IntegerField(default=0)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapters', to='audio_book.book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapter',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_c', to='audio_book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='narrator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_n', to='audio_book.narrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_w', to='audio_book.writer'),
        ),
    ]
