# Generated by Django 4.0.6 on 2022-07-06 13:22

import audio_book.models
import audio_book.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='Collections', max_length=100)),
                ('book_cover', models.ImageField(max_length=1023, upload_to=audio_book.models.books_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('book_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category_title', models.CharField(default='Other', max_length=100)),
                ('book_category_cover', models.ImageField(max_length=1023, upload_to=audio_book.models.book_categorys_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('book_category_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BookCategory',
                'verbose_name_plural': 'BookCategories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrator_name', models.CharField(default='unknown', max_length=100)),
                ('narrator_title', models.CharField(default='unknown', max_length=100)),
                ('narrator_cover', models.ImageField(max_length=1023, upload_to=audio_book.models.narrators_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('narrator_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Narrator',
                'verbose_name_plural': 'Narratores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default='unknown', max_length=100)),
                ('writer_title', models.CharField(default='unknown', max_length=100)),
                ('writer_cover', models.ImageField(max_length=1023, upload_to=audio_book.models.writers_cover_images, validators=[audio_book.validators.validate_image_extension])),
                ('writer_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(default='Unknown_chapter', max_length=100)),
                ('chapter_description', models.TextField(blank=True, max_length=100, null=True)),
                ('chapter_file', models.FileField(upload_to=audio_book.models.chapter_files, validators=[audio_book.validators.validate_track_extension])),
                ('chapter_status', models.BooleanField(default=False)),
                ('chapter_release_date', models.DateTimeField()),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapters', to='audio_book.book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapter',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_c', to='audio_book.bookcategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='narrator_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_n', to='audio_book.narrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_w', to='audio_book.writer'),
        ),
    ]
