# Generated by Django 4.0.6 on 2022-07-05 18:43

from django.db import migrations, models
import django.db.models.deletion
import podcast.models
import podcast.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Other', max_length=120)),
                ('category_description', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='unknown', max_length=50)),
                ('host_avatar', models.ImageField(blank=True, null=True, upload_to=podcast.models.hosts_cover_images, validators=[podcast.validators.validate_image_extension])),
                ('host_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(default='Collections', max_length=50)),
                ('season_cover', models.ImageField(upload_to=podcast.models.hosts_cover_images, validators=[podcast.validators.validate_image_extension])),
                ('season_description', models.TextField(blank=True, max_length=100, null=True)),
                ('season_release_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField(default=0)),
                ('host', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='podcast.host')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(default='Unknown_track', max_length=120)),
                ('episode_description', models.TextField(blank=True, max_length=100, null=True)),
                ('episode_file', models.FileField(null=True, upload_to=podcast.models.episode_files, validators=[podcast.validators.validate_track_extension])),
                ('user', models.IntegerField(default=0)),
                ('episode_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode', to='podcast.category')),
                ('season', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episodes', to='podcast.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['id'],
            },
        ),
    ]
