# Generated by Django 4.0.6 on 2022-07-07 07:11

from django.db import migrations, models
import django.db.models.deletion
import podcast.models
import podcast.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='unknown', max_length=100)),
                ('host_title', models.CharField(default='unknown', max_length=100)),
                ('host_cover', models.ImageField(max_length=1023, upload_to=podcast.models.hosts_cover_images, validators=[podcast.validators.validate_image_extension])),
                ('host_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_category_title', models.CharField(default='Other', max_length=100)),
                ('podcast_category_cover', models.ImageField(max_length=1023, upload_to=podcast.models.podcast_categorys_cover_images, validators=[podcast.validators.validate_image_extension])),
                ('podcast_category_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PodcastCategory',
                'verbose_name_plural': 'PodcastCategories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_title', models.CharField(default='Collections', max_length=100)),
                ('season_cover', models.ImageField(max_length=1023, upload_to=podcast.models.seasons_cover_images, validators=[podcast.validators.validate_image_extension])),
                ('season_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='podcast.host')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(default='Unknown_track', max_length=120)),
                ('episode_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('episode_file', models.FileField(null=True, upload_to=podcast.models.episode_files, validators=[podcast.validators.validate_track_extension])),
                ('episode_status', models.BooleanField(default=False)),
                ('episode_release_date', models.DateTimeField()),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast_category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode', to='podcast.podcastcategory')),
                ('season_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episodes', to='podcast.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['id'],
            },
        ),
    ]
