# Generated by Django 4.0.6 on 2022-07-05 18:43

from django.db import migrations, models
import radio.models
import radio.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(default='Unknown_radio', max_length=120)),
                ('station_frequency', models.FloatField(default=0)),
                ('station_url', models.CharField(default='', max_length=120)),
                ('station_description', models.TextField(blank=True, max_length=200, null=True)),
                ('cover_image', models.FileField(null=True, upload_to=radio.models.radio_cover_images, validators=[radio.validators.validate_image_extension])),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
                'ordering': ['id'],
            },
        ),
    ]
