# Generated by Django 4.0.6 on 2022-07-05 18:43

from django.db import migrations, models
import django.db.models.deletion
import music.models
import music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(default='Collections', max_length=50)),
                ('album_cover', models.ImageField(upload_to=music.models.albums_cover_images, validators=[music.validators.validate_image_extension])),
                ('album_description', models.TextField(blank=True, max_length=100, null=True)),
                ('album_release_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='unknown', max_length=50)),
                ('artist_avatar', models.ImageField(blank=True, null=True, upload_to=music.models.artists_cover_images, validators=[music.validators.validate_image_extension])),
                ('artist_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(default='Other', max_length=120)),
                ('genre_description', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(default='Unknown_track', max_length=120)),
                ('track_description', models.TextField(blank=True, max_length=100, null=True)),
                ('track_file', models.FileField(null=True, upload_to=music.models.track_files, validators=[music.validators.validate_track_extension])),
                ('user', models.IntegerField(default=0)),
                ('album', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='music.album')),
                ('track_genre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='track', to='music.genre')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='albums', to='music.artist'),
        ),
    ]
